version: '3.4'
networks:
  docker:
    driver: bridge

services:
  filesystemwatcher:
    image: ${DOCKER_REGISTRY-}filesystemwatcher
    build:
      context: .
      dockerfile: FileSystemWatcher/Dockerfile
    container_name: TelegrammBot
    environment:
    - DOTNET_USE_POLLING_FILE_WATCHER=true
    - APISettings__APIPoolingInverval=0.00:00:30
    - APISettings__FilePoolingInverval=0.00:00:15
    - DBOptions__ChatConnection=Server=DB;Port=3306;Database=ChatDB;Uid=root;Pwd=root;
    - DBOptions__SystemDataConnection=Server=DB;Port=3306;Database=SystemDataDB;Uid=root;Pwd=root;
    - DBOptions__DefaultConnection=Server=DB;Port=3306;Database=APPDB;Uid=root;Pwd=root;
        
    depends_on:
    - DB
    networks:
     - docker




  DB:
    image: mysql
    container_name: DB
    environment:
    - MYSQL_ROOT_PASSWORD=root
    networks:
     - docker
    volumes:
    - TelegrammDB:/var/lib/mysql




volumes:
  TelegrammDB:


  
